// CODE_BEGIN header
// GO generated by class generator: class generator 

package test.go
// CODE_END

// USER_CODE_BEGIN header

// USER_CODE_END

// CODE_BEGIN include
package main
// CODE_END

// USER_CODE_BEGIN includes

// USER CODE END

// CODE_BEGIN defines
const MAX_BUFFER_SIZE = 1024
const MAX_VALUES = 1024
// CODE_END

// USER_CODE_BEGIN defines

// USER CODE END

// CODE_BEGIN enums
type Status int
const (
    OK = 0
    ERROR = 1
    INPROGRESS = 1
    TEST = 10
    TEST2 = 1
)

type TEST int
const (
    OK = 0
    ERROR = 1
    INPROGRESS = 1
    TEST = 10
    TEST2 = 1
)
// CODE_END

// USER_CODE_BEGIN enums

// USER CODE END

// CODE_BEGIN classes
type test struct {
    id int16
    value int16
    array [10]int16

}

func test_example_function3(arg1 int16, arg2 int32)  {

}
func test_example_function4(arg1 int16, arg2 float32)  {

}
type system struct {
    id test
    voltage0 Status
    voltage1 int16
    voltage2 int16

}

func system_example_function(arg1 int16, arg2 float64)  {

}
// CODE_END

// USER_CODE_BEGIN classes

// USER CODE END

// CODE_BEGIN functions
func example_function1(arg1 int32, arg2 float32) int16 {

}
func example_function2(arg1 int16, arg2 float32) int32 {

}
// CODE_END

// USER_CODE_BEGIN functions

// USER CODE END